version: "3.6"
services:
  fastify:
    image: node:10
    container_name: bunq-automation
    environment:
      VIRTUAL_HOST: "${HOST}"
    expose:
      - ${SERVER_PORT}
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start