version: "3.6"
services:
  app:
    image: node:10
    container_name: bunq-automation-production
    environment:
      SERVER_PORT: "${SERVER_PORT:-8080}"
      SSL_SERVER_PORT: "${SSL_SERVER_PORT:-8443}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SSL_SERVER_PORT}:${SSL_SERVER_PORT}"
    volumes:
      - ./:/app
    working_dir: /app
    command: node build-server/Server.js

  react:
    image: node:10
    container_name: bunq-automation-react
    environment:
      PORT: "${PORT:-3000}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: 'yarn'
    command: ['run', 'react']

  server:
    image: node:10
    container_name: bunq-automation-server
    environment:
      SERVER_PORT: "${SERVER_PORT:-8080}"
      SSL_SERVER_PORT: "${SSL_SERVER_PORT:-8443}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SSL_SERVER_PORT}:${SSL_SERVER_PORT}"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: 'yarn'
    command: ['run', 'server']

  yarn:
    image: node:10
    volumes:
      - ./:/app
      - yarn:/usr/local/share/.cache/yarn/
    working_dir: /app
    entrypoint: 'yarn'
    command: []

volumes:
  yarn:

networks:
    default:
        external:
            name: bunq-automation
